#!/usr/bin/env bash
# detect-arch.sh — Detect host CPU architecture and write .env for docker compose
#
# Usage:
#   ./detect-arch.sh          # writes .env in current directory
#   source ./detect-arch.sh   # also exports vars into current shell
#
# Sets EMBED_BACKEND to:
#   fastembed              — x86_64 (native ONNX Runtime, fastest)
#   sentence-transformers  — ARM64 / Apple Silicon (native PyTorch)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

ARCH="$(uname -m)"

case "${ARCH}" in
    x86_64|amd64)
        EMBED_BACKEND="fastembed"
        ;;
    arm64|aarch64)
        EMBED_BACKEND="sentence-transformers"
        ;;
    *)
        echo "WARNING: Unknown architecture '${ARCH}', defaulting to sentence-transformers" >&2
        EMBED_BACKEND="sentence-transformers"
        ;;
esac

# Allow manual override via env
EMBED_BACKEND="${EMBED_BACKEND_OVERRIDE:-${EMBED_BACKEND}}"

# Preserve ENGRAM_REPO_DIR if already in .env, otherwise use default
if [ -f "${ENV_FILE}" ] && grep -q "^ENGRAM_REPO_DIR=" "${ENV_FILE}"; then
    ENGRAM_REPO_DIR="$(grep "^ENGRAM_REPO_DIR=" "${ENV_FILE}" | cut -d= -f2-)"
else
    ENGRAM_REPO_DIR="${ENGRAM_REPO_DIR:-${HOME}/engram-memory-community}"
fi

# Write .env (docker compose reads this automatically)
cat > "${ENV_FILE}" <<EOF
# Auto-generated by detect-arch.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Host architecture: ${ARCH}
EMBED_BACKEND=${EMBED_BACKEND}
ENGRAM_REPO_DIR=${ENGRAM_REPO_DIR}
EOF

echo "Detected arch: ${ARCH} → EMBED_BACKEND=${EMBED_BACKEND}"
echo "Wrote ${ENV_FILE}"

# Export for current shell if sourced
export EMBED_BACKEND
