#!/usr/bin/env bash
# detect-arch.sh — Detect host CPU architecture and write .env for docker compose
#
# Usage:
#   ./detect-arch.sh          # writes .env in current directory
#   source ./detect-arch.sh   # also exports vars into current shell
#
# fastembed 0.7.x uses ONNX Runtime with native ARM64 support,
# so no backend switching is needed — ONNX works on all architectures.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

ARCH="$(uname -m)"

# Preserve ENGRAM_REPO_DIR if already in .env, otherwise use default
if [ -f "${ENV_FILE}" ] && grep -q "^ENGRAM_REPO_DIR=" "${ENV_FILE}"; then
    ENGRAM_REPO_DIR="$(grep "^ENGRAM_REPO_DIR=" "${ENV_FILE}" | cut -d= -f2-)"
else
    ENGRAM_REPO_DIR="${ENGRAM_REPO_DIR:-${HOME}/engram-memory-community}"
fi

# Write .env (docker compose reads this automatically)
cat > "${ENV_FILE}" <<EOF
# Auto-generated by detect-arch.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Host architecture: ${ARCH}
# fastembed 0.7.x uses ONNX Runtime — native support for x86_64 and ARM64
ENGRAM_REPO_DIR=${ENGRAM_REPO_DIR}
EOF

echo "Detected arch: ${ARCH} (fastembed ONNX Runtime supports all architectures natively)"
echo "Wrote ${ENV_FILE}"
